development:
  adapter: postgresql
  encoding: unicode
  database: samppleapp_development
  username: sampleapp
  password: password
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: sampleapp_test
  username: sampleapp
  password: password
  pool: 5