# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1b5b224735b9b7cef9daf620d5e0b79c97dc90967e19bdab6656e677e9036dc2e0d7ebb1fb032b4a206b27d1db517c69c0627eadfc9e6c586b02f8832ed96f2

test:
  secret_key_base: bb04994361eb3d91d7115c1d4fd82a5a0616f0c0523c8f602748812a819b3f243f9a12bf8e405e35e226ee6f61817bccadd089e885e1387fa567b0461d819431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
